//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_model
    {
        public int Id_modelcar { get; set; }
        public string Name_modelcar { get; set; }
        public string Name_makecar { get; set; }
    
        public virtual Car_make Car_make { get; set; }
    }
}
