//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Reviews
    {
        public string Id_review { get; set; }
        public string Title_review { get; set; }
        public string Description_review { get; set; }
        public byte[] Picture_review { get; set; }
        public Nullable<int> Id_admin { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
