//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulters
    {
        public int Id_consulter { get; set; }
        public string Name_consulter { get; set; }
        public string Surname_consulter { get; set; }
        public string Fonction_consulter { get; set; }
        public string Email_consulter { get; set; }
        public string Password_consulter { get; set; }
        public int Id_admin { get; set; }
        public byte[] Picture_consulter { get; set; }
    }
}
