//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dream_carEntities : DbContext
    {
        public Dream_carEntities()
            : base("name=Dream_carEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Car_advice> Car_advice { get; set; }
        public virtual DbSet<Cars_Reviews> Cars_Reviews { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Consulters> Consulters { get; set; }
        public virtual DbSet<Car_make> Car_make { get; set; }
        public virtual DbSet<Car_model> Car_model { get; set; }
        public virtual DbSet<Car_type> Car_type { get; set; }
        public virtual DbSet<News_type> News_type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicule> Vehicule { get; set; }
        public virtual DbSet<Car_Model1> Car_Model1Set { get; set; }
    }
}
