//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string Id_news { get; set; }
        public string Title_news { get; set; }
        public string Description_news { get; set; }
        public byte[] Pic_news { get; set; }
        public Nullable<int> Id_admin { get; set; }
        public string Subtitle_news { get; set; }
        public string typenews_news { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual News_type News_type { get; set; }
    }
}
