//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id_user { get; set; }
        public string Name_user { get; set; }
        public string Surname_user { get; set; }
        public string Phonenumber_user { get; set; }
        public string City_user { get; set; }
        public string Adresse_user { get; set; }
        public string Email_user { get; set; }
        public string Password_user { get; set; }
    }
}
