//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream_car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public int Vehicule_ID { get; set; }
        public string Vehicule_Make { get; set; }
        public string Vehicule_Model { get; set; }
        public int Vehicule_Year { get; set; }
        public int Vehicule_Horsepower { get; set; }
        public int Vehicule_Kilometrage { get; set; }
        public Nullable<bool> Vehicule_FirstHand { get; set; }
        public int Vehicule_DoorsNumber { get; set; }
        public string Vehicule_Fuel { get; set; }
        public string Vehicule_Transmission { get; set; }
        public decimal Vehicule_SellPrice { get; set; }
        public byte[] Vehicule_Pictures { get; set; }
        public string Vehicule_Description { get; set; }
        public Nullable<System.DateTime> PostingTime { get; set; }
    }
}
